import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.explorer': 'Explorer',
    'nav.testnet': 'DpossAI',
    'nav.tokenomics': 'Tokenomics',
    'nav.roadmap': 'Roadmap',
    'nav.marketplace': 'Marketplace',
    'nav.dashboard': 'Dashboard',
    
    // Hero
    'hero.title': 'Democratizing the Future of Computing',
    'hero.subtitle': 'Turn idle hardware into passive income.',
    'hero.cta': 'Get Started',
    'hero.learn': 'Learn More',
    
    // Metrics
    'metrics.nodes': 'Active Nodes',
    'metrics.validators': 'Validators',
    'metrics.transactions': 'Transactions',
    'metrics.cities': 'Global Cities',
    
    // Features
    'features.nodes.title': 'Run Nodes',
    'features.nodes.desc': 'Deploy and manage blockchain nodes with enterprise-grade infrastructure',
    'features.validators.title': 'Become a Validator',
    'features.validators.desc': 'Secure the network and earn rewards by validating transactions',
    'features.rewards.title': 'Earn Rewards',
    'features.rewards.desc': 'Get rewarded for contributing to network security and growth',
    
    // Global Network
    'global.title': 'Global Validator Network',
    'global.subtitle': 'Real-time visualization of active validators around the world',
    'global.workerNodes': 'Worker Nodes',
    'global.contributors': 'Global Contributors',
    'global.cities': 'Active Cities',
    
    // Network Performance
    'network.title': 'Network Performance',
    'network.subtitle': 'Real-time DePIN infrastructure metrics',
    'network.performance': 'High Performance',
    'network.performanceDesc': 'Ultra-fast transaction processing with sub-second finality',
    'network.decentralized': 'Truly Decentralized',
    'network.decentralizedDesc': 'Distributed across thousands of nodes worldwide',
    'network.global': 'Global Infrastructure',
    'network.globalDesc': 'Operating in major cities across 6 continents',
    'network.community': 'Growing Community',
    'network.communityDesc': 'Join thousands of contributors building the future',
    
    // DePIN Metrics
    'depin.nodes': 'Active Nodes',
    'depin.validators': 'Validators',
    'depin.devices': 'Devices',
    'depin.uptime': 'Network Uptime',
    'depin.bandwidth': 'Bandwidth',
    'depin.bandwidthDesc': 'Global network throughput',
    'depin.compute': 'Compute',
    'depin.computeDesc': 'Processing power available',
    'depin.storage': 'Storage',
    'depin.storageDesc': 'Decentralized storage capacity',
    'depin.used': 'In use',
    'depin.viewExplorer': 'View DePIN Explorer',
    
    // CTA
    'cta.title': 'Ready to Join the Network?',
    'cta.subtitle': 'Start validating and earning rewards today',
    'cta.start': 'Start Validating',
    'cta.learn': 'Learn More',
    
    // Explorer
    'explorer.banner.title': 'Blockchain Successfully Validated in Tests',
    'explorer.banner.desc': 'Pozzer protocol DePIN has been tested and approved. The data below reflects the latest successful tests. Mainnet in active development - launch scheduled for Q2 2026.',
    'explorer.banner.cta': 'VIEW ROADMAP',
    'explorer.search.placeholder': 'Search by TX hash, block, or address...',
    'explorer.search.button': 'Search',
    'explorer.testnet.title': 'Testnet Live Network',
    'explorer.testnet.subtitle': 'Real-time DePIN network monitoring',
    'explorer.consensus.title': 'Distributed Consensus Mechanism',
    'explorer.consensus.subtitle': 'Real-time 2-of-3 distributed validator consensus',
    'explorer.consensus.current': 'Current Block',
    'explorer.consensus.progress': 'Consensus Progress',
    'explorer.consensus.votes': 'votes required',
    'explorer.consensus.finalized': '✓ Finalized',
    'explorer.consensus.validating': 'Validating...',
    'explorer.metrics.block': 'Block:',
    'explorer.metrics.uptime': 'uptime:',
    'explorer.metrics.nodes': 'nodes:',
    'explorer.metrics.devices': 'devices:',
    'explorer.validator': 'Validator',
    'explorer.blocks.title': 'Recent Blocks',
    'explorer.blocks.number': 'Block',
    'explorer.blocks.hash': 'Hash',
    'explorer.blocks.txCount': 'Transactions',
    'explorer.blocks.time': 'Time',
    'explorer.transactions.title': 'Recent Transactions',
    'explorer.transactions.hash': 'Transaction Hash',
    'explorer.transactions.from': 'From',
    'explorer.transactions.to': 'To',
    'explorer.transactions.amount': 'Amount',
    'explorer.transactions.status': 'Status',
    'explorer.searchPlaceholder': 'Search by TX hash, block, or address...',
    'explorer.searchButton': 'Search',
    'explorer.liveNetwork': 'Testnet Live Network',
    'explorer.liveNetworkDesc': 'Real-time DePIN network monitoring',
    'explorer.uptime': 'uptime',
    'explorer.nodes': 'nodes',
    'explorer.devices': 'devices',
    'explorer.recentBlocks': 'Recent Blocks',
    'explorer.recentTransactions': 'Recent Transactions',
    'explorer.live': 'LIVE',
    'explorer.offline': 'OFFLINE',
    'explorer.loadingBlocks': 'Loading blocks...',
    'explorer.waitingConnection': 'Waiting for connection...',
    'explorer.loadingTransactions': 'Loading transactions...',
    'explorer.blockchainEvents': 'Blockchain Events',
    'explorer.realEventsOnly': 'Real events only',
    'explorer.waitingActivity': 'Waiting for blockchain activity...',
    'explorer.networkHealth': 'Network Health',
    'explorer.excellent': 'Excellent',
    'explorer.good': 'Good',
    'explorer.fair': 'Fair',
    'explorer.degraded': 'Degraded',
    'explorer.activeNodes': 'Active Nodes',
    'explorer.blocksValidated': 'Blocks Validated',
    'explorer.realBlockchain': 'Real blockchain testnet',
    'explorer.networkUptime': 'Network Uptime',
    'explorer.stableTestnet': 'Stable testnet',
    'explorer.latestBlock': 'Latest Block',
    'explorer.testnetOnline': 'Testnet Online',
    'explorer.disconnectedStatus': 'Disconnected',
    'explorer.geographicDist': 'Geographic Distribution',
    'explorer.nodesByRegion': 'Nodes distributed across regions',
    'explorer.nodeTypes': 'Node Types',
    'explorer.infraByType': 'Infrastructure by type',
    'explorer.networkProviders': 'Network Providers',
    'explorer.activeProviders': 'Active infrastructure providers',
    'explorer.all': 'All',
    'explorer.compute': 'Compute',
    'explorer.storage': 'Storage',
    'explorer.bandwidth': 'Bandwidth',
    'explorer.iot': 'IoT',
    'explorer.validated': 'blocks',
    'explorer.active': 'Active',
    'explorer.idle': 'Idle',
    'explorer.footerDesc': 'Decentralized Physical Infrastructure Network - Real testnet running',
    'explorer.realTestnet': 'Real Testnet Active',
    'explorer.infrastructure': 'Infrastructure',
    'explorer.computeNodes': 'Compute Nodes',
    'explorer.storageNetwork': 'Storage Network',
    'explorer.bandwidthProviders': 'Bandwidth Providers',
    'explorer.iotGateway': 'IoT Gateway',
    'explorer.providers': 'Providers',
    'explorer.becomeProvider': 'Become a Provider',
    'explorer.hardwareReq': 'Hardware Requirements',
    'explorer.providerGuide': 'Provider Guide',
    'explorer.resources': 'Resources',
    'explorer.apiDocs': 'API Documentation',
    'explorer.networkStats': 'Network Statistics',
    'explorer.devPortal': 'Developer Portal',
    'explorer.support': 'Support',
    'explorer.copyright': '© 2025 Pozzer DePIN. All rights reserved.',
    'explorer.connected': 'Connected',
    'nav.becomeNode': 'Become a Node',
    
    // Testnet Countdown
    'testnet.countdown.title': 'TESTNET LAUNCHING SOON',
    'testnet.countdown.description': 'Prepare your wallet and get ready to join the revolution',
    'testnet.countdown.days': 'Days',
    'testnet.countdown.hours': 'Hours',
    'testnet.countdown.minutes': 'Minutes',
    'testnet.countdown.seconds': 'Seconds',
    'testnet.countdown.earlyAccess': 'Early Access Password',
    'testnet.countdown.enterPassword': 'Enter password',
    'testnet.countdown.unlock': 'Unlock',
    'testnet.countdown.wrongPassword': 'Incorrect password',
    'testnet.countdown.error': 'An error occurred',
    'testnet.countdown.followUs': 'Follow us for updates:',
    
    // Testnet Beta
    'testnet.hero.badge': 'DpossAI Active',
    'testnet.rewards.totalPZR': 'Total PZR',
    'testnet.rewards.viewPrevious': 'View previous rewards',
    'testnet.rewards.nodeReward': 'Node Reward',
    'testnet.rewards.inviteReward': 'Invite Reward',
    'testnet.rewards.socialReward': 'Social Reward',
    'testnet.referral.title': 'Invite your friends and earn 10% per invite!',
    'testnet.referral.share': 'Share',
    'testnet.referral.validInvites': 'Valid Invites',
    'testnet.referral.inviteReward': 'Invite Reward',
    'testnet.missions.node.title': 'Node Missions',
    'testnet.missions.node.getDevnet': 'Get Devnet Solution',
    'testnet.missions.node.becomeWorker': 'Become a Worker Node',
    'testnet.missions.node.becomeValidator': 'Become a Validator Node',
    'testnet.missions.node.delegate': 'Delegate to a Validator',
    'testnet.missions.node.stakeRedeem': 'Stake or Redeem Extra',
    'testnet.missions.social.title': 'Social Missions',
    'testnet.missions.social.claimable': 'Claimable PZR',
    'testnet.missions.social.records': 'Records',
    'testnet.missions.social.claim': 'Claim',
    'testnet.missions.social.generalTitle': 'General Missions',
    'testnet.missions.social.dailyTitle': 'Daily Missions',
    'testnet.missions.social.followX': 'Follow Pozzer on X',
    'testnet.missions.social.joinDiscord': 'Join Discord',
    'testnet.missions.social.joinTelegram': 'Join Telegram',
    'testnet.missions.social.followFounder': 'Follow Founder on X',
    'testnet.missions.daily.likePost': 'Like a post',
    'testnet.missions.daily.repost': 'Repost',
    'testnet.missions.daily.reply': 'Reply to a post',
    'testnet.missions.daily.postAbout': 'Post about Pozzer',
    
    // Transaction Details
    'explorer.backToExplorer': 'Back to Explorer',
    'explorer.loadingTransaction': 'Loading transaction...',
    'explorer.transactionNotFound': 'Transaction Not Found',
    'explorer.transactionNotFoundDesc': 'The transaction you are looking for does not exist or may have been pruned.',
    'explorer.transactionDetails': 'Transaction Details',
    'explorer.transactionDetailsDesc': 'Complete information about this blockchain transaction',
    'explorer.transactionHash': 'Transaction Hash',
    'explorer.transactionType': 'Transaction Type',
    'explorer.fileSize': 'File Size',
    'explorer.timestamp': 'Timestamp',
    'explorer.blockNumber': 'Block Number',
    'explorer.transactionFlow': 'Transaction Flow',
    'explorer.from': 'From',
    'explorer.to': 'To',
    
    // Differentials
    'diff.title': 'POZZER DIFFERENTIALS',
    'diff.platform.title': '4-in-1 Platform',
    'diff.platform.desc': 'The only DePIN protocol with storage + compute + bandwidth + IoT integrated',
    'diff.setup.title': 'Instant Setup',
    'diff.setup.desc': '5 minutes to connect hardware vs 2-3h from competitors',
    'diff.payments.title': 'Hourly Payments',
    'diff.payments.desc': 'Get paid every hour vs weekly/monthly from competitors',
    'diff.hardware.title': 'Common Hardware',
    'diff.hardware.desc': 'Any PC/server works - no enterprise requirements',
    
    // Footer
    'footer.rights': 'All rights reserved.',
    'footer.community': 'Join our community',
    
    // Testnet Page
    'testnet.hero.title': 'Testnet Beta',
    'testnet.hero.subtitle': 'Connect your wallet, complete missions and earn XP',
    'testnet.connectWallet': 'Connect Wallet',
    'testnet.overlay.title': 'Connect to Access Testnet',
    'testnet.overlay.description': 'Connect your wallet to start earning XP and completing missions.',
    'testnet.selectWallet': 'Select Wallet',
    'testnet.selectWalletDesc': 'Choose your preferred wallet to connect',
    'testnet.cancel': 'Cancel',
    'testnet.disconnect': 'Disconnect',
    'testnet.missions': 'Missions',
    'testnet.level': 'Level',
    'testnet.nodesOnline': 'Nodes Online',
    'testnet.done': 'Done',
    'testnet.claim': 'Claim',
    'testnet.verify': 'Verify',
    'testnet.daily': 'Daily',
    'testnet.gettingStarted': 'Getting Started with Pozzer',
    'testnet.gettingStartedDesc': 'Complete these steps to set up your node and start earning XP',
    'testnet.connect': 'Connect',
    'testnet.meetDpossAI': 'Meet DpossAI',
    'testnet.start': 'Start',
    'testnet.copyLink': 'Copy Link',
    'testnet.yourProgress': 'Your Progress',
    'testnet.progressDesc': 'Each milestone unlocks real mainnet benefits',
    'testnet.currentLevel': 'Current Level',
    'testnet.nextMilestone': 'Next milestone',
    'testnet.activityMatters': 'YOUR TESTNET ACTIVITY MATTERS',
    'testnet.bridgeTitle': 'What you earn now → What you get at mainnet',
    'testnet.bridgeDesc': 'Every PZR, mission, and referral in testnet directly impacts your mainnet position',
    'testnet.snapshot': 'Mainnet snapshot',
    'testnet.snapshotDesc': 'will be taken at testnet close. Your score, PZR balance, and referrals are permanently recorded on-chain.',
    'testnet.nodeMissions': 'Node Missions',
    'testnet.nodeMissionsDesc': 'Run nodes and earn XP for contributing to the network',
    'testnet.socialMissions': 'Social Missions',
    'testnet.socialMissionsDesc': 'Grow the community and earn XP',
    'testnet.nodeSimulators': 'Node Simulators',
    'testnet.nodeSimulatorsDesc': "Test what it's like to operate a node and see earnings estimates",
    'testnet.estEarnings': 'Est. Earnings',
    'testnet.simulating': 'SIMULATING',
    'testnet.simulated': 'simulated',
    'testnet.stopSimulation': 'Stop Simulation',
    'testnet.startSimulation': 'Start Simulation',
    'testnet.howToParticipate': 'How to Participate',
    'testnet.howToParticipateDesc': 'Choose your role in the Pozzer network — from active node operators to passive delegators',
    'testnet.nodeType': 'Node Type',
    'testnet.whatItDoes': 'What it does',
    'testnet.needsMachine': 'Needs machine?',
    'testnet.reward': 'Reward',
    'testnet.yes': 'Yes',
    'testnet.no': 'No',
    'testnet.testnetNote': 'Testnet note',
    'testnet.testnetNoteDesc': 'During testnet, all node types are simulated — no real machine required. At mainnet launch, Worker and Verifier nodes will require the Pozzer node client and an NFT License.',
    'testnet.referralProgram': 'Referral Program',
    'testnet.referralDesc': 'Invite friends, earn +200 XP each',
    'testnet.connectForReferral': 'Connect wallet to get your referral link',
    'testnet.copied': 'Copied',
    'testnet.copy': 'Copy',
    'testnet.invited': 'Invited',
    'testnet.bonusXP': 'Bonus XP',
    'testnet.pending': 'Pending',
    'testnet.earnCalculator': 'Earn Calculator',
    'testnet.earnCalculatorDesc': 'Estimate your potential returns',
    'testnet.launchPrice': 'Launch Price',
    'testnet.friendsReferred': 'Friends Referred',
    'testnet.baseValue': 'Base Value',
    'testnet.leaderboard': 'Leaderboard',
    'testnet.rank': 'Rank',
    'testnet.profile': 'Profile',
    'testnet.inviteReward': 'Invite Reward',
    'testnet.totalReward': 'Total Reward',
    'testnet.address': 'Address',
    'testnet.you': 'YOU',
    'testnet.noLeaderboardYet': 'No participants yet. Be the first!',
    // Mainnet Rewards
    'testnet.rewards.title': 'MAINNET REWARDS BY TIER',
    'testnet.rewards.subtitle': 'Your XP level unlocks exclusive benefits when mainnet launches',
    'testnet.rewards.yourTier': 'YOUR TIER',
    'testnet.rewards.boost': 'Boost',
    'testnet.rewards.needsXP': 'Needs {{xp}} XP',
    'testnet.rewards.explorer': 'Explorer',
    'testnet.rewards.explorerReward1': 'Small airdrop',
    'testnet.rewards.explorerReward2': 'Mainnet access',
    'testnet.rewards.operator': 'Operator',
    'testnet.rewards.operatorReward1': 'Medium airdrop',
    'testnet.rewards.operatorReward2': 'Top 100: 80% NFT discount',
    'testnet.rewards.operatorReward3': '1.3x allocation boost',
    'testnet.rewards.validator': 'Validator',
    'testnet.rewards.validatorReward1': 'Large airdrop',
    'testnet.rewards.validatorReward2': 'Top 500: 50% NFT discount',
    'testnet.rewards.validatorReward3': 'Validator priority',
    'testnet.rewards.validatorReward4': '1.6x allocation boost',
    'testnet.rewards.genesis': 'Genesis Operator',
    'testnet.rewards.genesisReward1': 'Maximum airdrop',
    'testnet.rewards.genesisReward2': 'Top 21: FREE NFT License',
    'testnet.rewards.genesisReward3': 'Guaranteed validator slot',
    'testnet.rewards.genesisReward4': 'Top 21 ranking',
    'testnet.rewards.genesisReward5': '2x allocation boost',
    'testnet.rewards.tipTitle': 'How Allocation Boost Works',
    'testnet.rewards.tipDesc': 'Your tier multiplies your base airdrop. Example: 2000 PZR base × Genesis 2x = 4000 PZR total.',
    'testnet.bridge.xpEarned': 'XP Earned',
    'testnet.bridge.xpBonus': 'Bonus',
    'testnet.bridge.missionsDone': 'Missions',
    'testnet.bridge.freeNFT': 'Free NFT',
    'testnet.bridge.priorityQueue': 'Priority Queue',
    'testnet.bridge.moreForPriority': 'more for priority',
    'testnet.bridge.referralShared': 'Referrals',
    'testnet.bridge.topReferrers': 'Top Referrers',
    'testnet.bridge.level': 'Level',
    'testnet.chat.whatIsDepin': 'What is DePIN?',
    'testnet.chat.howEarn': 'How do I earn more?',
    'testnet.chat.referralTips': 'Referral tips',
    'testnet.chat.placeholder': 'Ask DpossAI...',
    'testnet.notif.walletConnected': '✅ Wallet connected! Welcome to Pozzer Testnet.',
    'testnet.notif.connectFirst': '⚠️ Connect your wallet first!',
    'testnet.notif.missionComplete': 'Mission complete!',
    'testnet.notif.linkCopied': '✅ Referral link copied!',
    'testnet.notif.onboardingComplete': '🎉 Onboarding complete! You are ready to earn XP.',
    'testnet.notif.verifyAction': 'Please complete the action, then click Verify to claim your XP',
    // Mission titles
    'testnet.mission.provider': 'Provider Node',
    'testnet.mission.providerDesc': 'Share computing resources',
    'testnet.mission.validator': 'Validator',
    'testnet.mission.validatorDesc': 'Validate network transactions',
    'testnet.mission.worker': 'Worker Node',
    'testnet.mission.workerDesc': 'Execute distributed tasks',
    'testnet.mission.delegate': 'Delegate to Validator',
    'testnet.mission.delegateDesc': 'Delegate stake to a validator',
    'testnet.mission.install': 'Install Software',
    'testnet.mission.installDesc': 'Setup node software',
    'testnet.mission.twitter': 'Follow on Twitter',
    'testnet.mission.twitterDesc': 'Follow @pozzer_depin',
    'testnet.mission.telegram': 'Join Telegram',
    'testnet.mission.telegramDesc': 'Join official group',
    'testnet.mission.post': 'Post about Pozzer',
    'testnet.mission.postDesc': 'Share on Twitter',
    'testnet.mission.daily': 'Daily Share',
    'testnet.mission.dailyDesc': 'Share daily',
    // Simulators
    'testnet.sim.provider': 'Provider Node',
    'testnet.sim.providerDesc': 'Share bandwidth & compute',
    'testnet.sim.validator': 'Validator Node',
    'testnet.sim.validatorDesc': 'Validate transactions',
    'testnet.sim.worker': 'Worker Node',
    'testnet.sim.workerDesc': 'Process distributed tasks',
    // Milestones (XP-based levels)
    'testnet.milestone.newbie': 'Newbie',
    'testnet.milestone.newbieReward': 'Just getting started',
    'testnet.milestone.newbieMainnet': 'Connect wallet to begin',
    'testnet.milestone.explorer': 'Explorer',
    'testnet.milestone.explorerReward': 'Access to Node Simulators',
    'testnet.milestone.explorerMainnet': 'Testnet participant badge',
    'testnet.milestone.operator': 'Operator',
    'testnet.milestone.operatorReward': 'DpossAI advanced tips unlocked',
    'testnet.milestone.operatorMainnet': '+15% mainnet allocation bonus',
    'testnet.milestone.validator': 'Validator',
    'testnet.milestone.validatorReward': 'Priority NFT License queue',
    'testnet.milestone.validatorMainnet': 'Free NFT License at mainnet',
    'testnet.milestone.genesis': 'Genesis Operator',
    'testnet.milestone.genesisReward': 'Early validator slot reserved',
    'testnet.milestone.genesisMainnet': 'Validator slot + 2x allocation',
    // Onboarding
    'testnet.onboard.wallet': 'Connect your wallet',
    'testnet.onboard.walletDesc': 'Link your wallet to start earning XP',
    'testnet.onboard.dpossai': 'Meet DpossAI',
    'testnet.onboard.dpossaiDesc': 'Your AI agent will guide your journey',
    'testnet.onboard.mission': 'Complete your first mission',
    'testnet.onboard.missionDesc': 'Follow us on Twitter or join Telegram',
    'testnet.onboard.invite': 'Invite a friend',
    'testnet.onboard.inviteDesc': 'Share your referral link for +200 XP',
    // Node types
    'testnet.nodeType.worker': 'Worker Node',
    'testnet.nodeType.workerWhat': 'Executes distributed tasks delegated by the network',
    'testnet.nodeType.workerReward': 'Reward per task executed',
    'testnet.nodeType.verifier': 'Verifier Node',
    'testnet.nodeType.verifierWhat': 'Verifies and validates results from Worker Nodes',
    'testnet.nodeType.verifierReward': 'Reward per validation',
    'testnet.nodeType.delegator': 'Delegator',
    'testnet.nodeType.delegatorWhat': 'Lends tokens to nodes to increase their stake power',
    'testnet.nodeType.delegatorReward': 'Share of node rewards',
    'testnet.nodeType.delegating': 'Delegating',
    'testnet.nodeType.delegatingWhat': 'Action of delegating tokens to an active node',
    'testnet.nodeType.delegatingReward': 'Passive yield on staked PZR',
  },
  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.explorer': 'Explorador',
    'nav.testnet': 'DpossAI',
    'nav.tokenomics': 'Tokenomics',
    'nav.roadmap': 'Roadmap',
    'nav.marketplace': 'Marketplace',
    'nav.dashboard': 'Painel',
    
    // Hero
    'hero.title': 'Democratizando o Futuro da Computação',
    'hero.subtitle': 'Transforme hardware ocioso em renda passiva.',
    'hero.cta': 'Começar',
    'hero.learn': 'Saiba Mais',
    
    // Metrics
    'metrics.nodes': 'Nós Ativos',
    'metrics.validators': 'Validadores',
    'metrics.transactions': 'Transações',
    'metrics.cities': 'Cidades Globais',
    
    // Features
    'features.nodes.title': 'Execute Nós',
    'features.nodes.desc': 'Implante e gerencie nós blockchain com infraestrutura de nível empresarial',
    'features.validators.title': 'Torne-se um Validador',
    'features.validators.desc': 'Proteja a rede e ganhe recompensas validando transações',
    'features.rewards.title': 'Ganhe Recompensas',
    'features.rewards.desc': 'Seja recompensado por contribuir para a segurança e crescimento da rede',
    
    // Global Network
    'global.title': 'Rede Global de Validadores',
    'global.subtitle': 'Visualização em tempo real de validadores ativos ao redor do mundo',
    'global.workerNodes': 'Nós Trabalhadores',
    'global.contributors': 'Contribuidores Globais',
    'global.cities': 'Cidades Ativas',
    
    // Network Performance
    'network.title': 'Desempenho da Rede',
    'network.subtitle': 'Métricas de infraestrutura DePIN em tempo real',
    'network.performance': 'Alta Performance',
    'network.performanceDesc': 'Processamento ultra-rápido de transações com finalização em menos de um segundo',
    'network.decentralized': 'Verdadeiramente Descentralizada',
    'network.decentralizedDesc': 'Distribuída entre milhares de nós ao redor do mundo',
    'network.global': 'Infraestrutura Global',
    'network.globalDesc': 'Operando em grandes cidades em 6 continentes',
    'network.community': 'Comunidade em Crescimento',
    'network.communityDesc': 'Junte-se a milhares de contribuidores construindo o futuro',
    
    // DePIN Metrics
    'depin.nodes': 'Nós Ativos',
    'depin.validators': 'Validadores',
    'depin.devices': 'Dispositivos',
    'depin.uptime': 'Uptime da Rede',
    'depin.bandwidth': 'Largura de Banda',
    'depin.bandwidthDesc': 'Throughput global da rede',
    'depin.compute': 'Computação',
    'depin.computeDesc': 'Poder de processamento disponível',
    'depin.storage': 'Armazenamento',
    'depin.storageDesc': 'Capacidade de armazenamento descentralizado',
    'depin.used': 'Em uso',
    'depin.viewExplorer': 'Ver Explorer DePIN',
    
    // CTA
    'cta.title': 'Pronto para Entrar na Rede?',
    'cta.subtitle': 'Comece a validar e ganhar recompensas hoje',
    'cta.start': 'Começar a Validar',
    'cta.learn': 'Saiba Mais',
    
    // Explorer
    'explorer.banner.title': 'Blockchain Validado com Sucesso em Testes',
    'explorer.banner.desc': 'Pozzer protocol DePIN foi testado e aprovado. Os dados abaixo refletem os testes mais recentes. Mainnet em desenvolvimento ativo - lançamento previsto para Q2 2026.',
    'explorer.banner.cta': 'VER ROADMAP',
    'explorer.search.placeholder': 'Buscar por hash TX, bloco ou endereço...',
    'explorer.search.button': 'Buscar',
    'explorer.testnet.title': 'Rede Testnet ao Vivo',
    'explorer.testnet.subtitle': 'Monitoramento de rede DePIN em tempo real',
    'explorer.consensus.title': 'Mecanismo de Consenso Distribuído',
    'explorer.consensus.subtitle': 'Consenso 2-de-3 validadores distribuído em tempo real',
    'explorer.consensus.current': 'Bloco Atual',
    'explorer.consensus.progress': 'Progresso do Consenso',
    'explorer.consensus.votes': 'votos necessários',
    'explorer.consensus.finalized': '✓ Finalizado',
    'explorer.consensus.validating': 'Validando...',
    'explorer.metrics.block': 'Bloco:',
    'explorer.metrics.uptime': 'uptime:',
    'explorer.metrics.nodes': 'nós:',
    'explorer.metrics.devices': 'dispositivos:',
    'explorer.validator': 'Validador',
    'explorer.blocks.title': 'Blocos Recentes',
    'explorer.blocks.number': 'Bloco',
    'explorer.blocks.hash': 'Hash',
    'explorer.blocks.txCount': 'Transações',
    'explorer.blocks.time': 'Hora',
    'explorer.transactions.title': 'Transações Recentes',
    'explorer.transactions.hash': 'Hash da Transação',
    'explorer.transactions.from': 'De',
    'explorer.transactions.to': 'Para',
    'explorer.transactions.amount': 'Quantia',
    'explorer.transactions.status': 'Status',
    'explorer.searchPlaceholder': 'Buscar por hash TX, bloco ou endereço...',
    'explorer.searchButton': 'Buscar',
    'explorer.liveNetwork': 'Rede Testnet ao Vivo',
    'explorer.liveNetworkDesc': 'Monitoramento de rede DePIN em tempo real',
    'explorer.uptime': 'uptime',
    'explorer.nodes': 'nós',
    'explorer.devices': 'dispositivos',
    'explorer.recentBlocks': 'Blocos Recentes',
    'explorer.recentTransactions': 'Transações Recentes',
    'explorer.live': 'AO VIVO',
    'explorer.offline': 'DESCONECTADO',
    'explorer.loadingBlocks': 'Carregando blocos...',
    'explorer.waitingConnection': 'Aguardando conexão...',
    'explorer.loadingTransactions': 'Carregando transações...',
    'explorer.blockchainEvents': 'Eventos da Blockchain',
    'explorer.realEventsOnly': 'Apenas eventos reais',
    'explorer.waitingActivity': 'Aguardando atividade da blockchain...',
    'explorer.networkHealth': 'Saúde da Rede',
    'explorer.excellent': 'Excelente',
    'explorer.good': 'Bom',
    'explorer.fair': 'Regular',
    'explorer.degraded': 'Degradado',
    'explorer.activeNodes': 'Nós Ativos',
    'explorer.blocksValidated': 'Blocos Validados',
    'explorer.realBlockchain': 'Testnet blockchain real',
    'explorer.networkUptime': 'Uptime da Rede',
    'explorer.stableTestnet': 'Testnet estável',
    'explorer.latestBlock': 'Último Bloco',
    'explorer.testnetOnline': 'Testnet Online',
    'explorer.disconnectedStatus': 'Desconectado',
    'explorer.geographicDist': 'Distribuição Geográfica',
    'explorer.nodesByRegion': 'Nós distribuídos por regiões',
    'explorer.nodeTypes': 'Tipos de Nós',
    'explorer.infraByType': 'Infraestrutura por tipo',
    'explorer.networkProviders': 'Provedores da Rede',
    'explorer.activeProviders': 'Provedores de infraestrutura ativos',
    'explorer.all': 'Todos',
    'explorer.compute': 'Computação',
    'explorer.storage': 'Armazenamento',
    'explorer.bandwidth': 'Largura de Banda',
    'explorer.iot': 'IoT',
    'explorer.validated': 'blocos',
    'explorer.active': 'Ativo',
    'explorer.idle': 'Inativo',
    'explorer.footerDesc': 'Rede de Infraestrutura Física Descentralizada - Testnet real em execução',
    'explorer.realTestnet': 'Testnet Real Ativa',
    'explorer.infrastructure': 'Infraestrutura',
    'explorer.computeNodes': 'Nós de Computação',
    'explorer.storageNetwork': 'Rede de Armazenamento',
    'explorer.bandwidthProviders': 'Provedores de Largura de Banda',
    'explorer.iotGateway': 'Gateway IoT',
    'explorer.providers': 'Provedores',
    'explorer.becomeProvider': 'Torne-se um Provedor',
    'explorer.hardwareReq': 'Requisitos de Hardware',
    'explorer.providerGuide': 'Guia do Provedor',
    'explorer.resources': 'Recursos',
    'explorer.apiDocs': 'Documentação da API',
    'explorer.networkStats': 'Estatísticas da Rede',
    'explorer.devPortal': 'Portal do Desenvolvedor',
    'explorer.support': 'Suporte',
    'explorer.copyright': '© 2025 Pozzer DePIN. Todos os direitos reservados.',
    'explorer.connected': 'Conectado',
    'nav.becomeNode': 'Torne-se um Nó',
    
    // Testnet Beta
    'testnet.hero.badge': 'DpossAI Ativo',
    'testnet.hero.title': 'Testnet Beta',
    'testnet.hero.subtitle': 'Complete missões, ganhe XP e ajude-nos a testar a rede',
    'testnet.rewards.totalPZR': 'Total PZR',
    'testnet.rewards.viewPrevious': 'Ver recompensas anteriores',
    'testnet.rewards.nodeReward': 'Recompensa do nó',
    'testnet.rewards.inviteReward': 'Recompensa por convite',
    'testnet.rewards.socialReward': 'Recompensa social',
    'testnet.referral.title': 'Convide seus amigos e ganhe 10% por cada convite!',
    'testnet.referral.share': 'Compartilhar',
    'testnet.referral.validInvites': 'Convites válidos',
    'testnet.referral.inviteReward': 'Recompensa por convite',
    'testnet.missions.node.title': 'Missões de nó',
    'testnet.missions.node.getDevnet': 'Obtenha a solução Devnet',
    'testnet.missions.node.becomeWorker': 'Torne-se um nó de trabalho',
    'testnet.missions.node.becomeValidator': 'Torne-se um Validador',
    'testnet.missions.node.delegate': 'Delegar a um Validador',
    'testnet.missions.node.stakeRedeem': 'Aposte ou resgate extra',
    'testnet.missions.social.title': 'Missões Sociais',
    'testnet.missions.social.claimable': 'PZR Resgatável',
    'testnet.missions.social.records': 'Registros',
    'testnet.missions.social.claim': 'Resgatar',
    'testnet.missions.social.generalTitle': 'Missões Gerais',
    'testnet.missions.social.dailyTitle': 'Missões diárias',
    'testnet.missions.social.followX': 'Siga Pozzer no X',
    'testnet.missions.social.joinDiscord': 'Entre no Discord',
    'testnet.missions.social.joinTelegram': 'Entre no Telegram',
    'testnet.missions.social.followFounder': 'Siga o fundador no X',
    'testnet.missions.daily.likePost': 'Curtir uma publicação',
    'testnet.missions.daily.repost': 'Repostar',
    'testnet.missions.daily.reply': 'Responder a uma publicação',
    'testnet.missions.daily.postAbout': 'Postar sobre Pozzer',
    
    // Transaction Details
    'explorer.backToExplorer': 'Voltar ao Explorador',
    'explorer.loadingTransaction': 'Carregando transação...',
    'explorer.transactionNotFound': 'Transação Não Encontrada',
    'explorer.transactionNotFoundDesc': 'A transação que você está procurando não existe ou pode ter sido removida.',
    'explorer.transactionDetails': 'Detalhes da Transação',
    'explorer.transactionDetailsDesc': 'Informações completas sobre esta transação blockchain',
    'explorer.transactionHash': 'Hash da Transação',
    'explorer.transactionType': 'Tipo de Transação',
    'explorer.fileSize': 'Tamanho do Arquivo',
    'explorer.timestamp': 'Data/Hora',
    'explorer.blockNumber': 'Número do Bloco',
    'explorer.transactionFlow': 'Fluxo da Transação',
    'explorer.from': 'De',
    'explorer.to': 'Para',
    
    // Differentials
    'diff.title': 'DIFERENCIAIS POZZER',
    'diff.platform.title': 'Plataforma 4-em-1',
    'diff.platform.desc': 'Único protocolo DePIN com storage + compute + bandwidth + IoT integrados',
    'diff.setup.title': 'Setup Instantâneo',
    'diff.setup.desc': '5 minutos para conectar hardware vs 2-3h dos concorrentes',
    'diff.payments.title': 'Pagamentos Horários',
    'diff.payments.desc': 'Receba a cada hora vs semanal/mensal da concorrência',
    'diff.hardware.title': 'Hardware Comum',
    'diff.hardware.desc': 'Qualquer PC/servidor funciona - sem requisitos enterprise',
    
    // Footer
    'footer.rights': 'Todos os direitos reservados.',
    'footer.community': 'Junte-se à nossa comunidade',
    
    // Testnet Page (basic keys that weren't in the detailed section above)
    'testnet.connectWallet': 'Conectar Carteira',
    'testnet.overlay.title': 'Conecte para Acessar a Testnet',
    'testnet.overlay.description': 'Conecte sua carteira para começar a ganhar XP e completar missões.',
    'testnet.selectWallet': 'Selecionar Carteira',
    'testnet.selectWalletDesc': 'Escolha sua carteira preferida para conectar',
    'testnet.cancel': 'Cancelar',
    'testnet.disconnect': 'Desconectar',
    'testnet.missions': 'Missões',
    'testnet.level': 'Nível',
    'testnet.nodesOnline': 'Nós Online',
    'testnet.done': 'Feito',
    'testnet.claim': 'Resgatar',
    'testnet.verify': 'Verificar',
    'testnet.daily': 'Diário',
    'testnet.gettingStarted': 'Começando com Pozzer',
    'testnet.gettingStartedDesc': 'Complete estes passos para configurar seu nó e começar a ganhar XP',
    'testnet.connect': 'Conectar',
    'testnet.meetDpossAI': 'Conhecer DpossAI',
    'testnet.start': 'Iniciar',
    'testnet.copyLink': 'Copiar Link',
    'testnet.yourProgress': 'Seu Progresso',
    'testnet.progressDesc': 'Cada milestone desbloqueia benefícios reais na mainnet',
    'testnet.currentLevel': 'Nível Atual',
    'testnet.nextMilestone': 'Próximo milestone',
    'testnet.activityMatters': 'SUA ATIVIDADE NA TESTNET IMPORTA',
    'testnet.bridgeTitle': 'O que você ganha agora → O que recebe na mainnet',
    'testnet.bridgeDesc': 'Cada PZR, missão e referência na testnet impacta diretamente sua posição na mainnet',
    'testnet.snapshot': 'Snapshot da mainnet',
    'testnet.snapshotDesc': 'será feito no fechamento da testnet. Sua pontuação, saldo PZR e referências serão registrados permanentemente on-chain.',
    'testnet.nodeMissions': 'Missões de Nó',
    'testnet.nodeMissionsDesc': 'Execute nós e ganhe XP por contribuir com a rede',
    'testnet.socialMissions': 'Missões Sociais',
    'testnet.socialMissionsDesc': 'Cresça a comunidade e ganhe XP',
    'testnet.nodeSimulators': 'Simuladores de Nó',
    'testnet.nodeSimulatorsDesc': 'Teste como é operar um nó e veja estimativas de ganhos',
    'testnet.estEarnings': 'Ganhos Est.',
    'testnet.simulating': 'SIMULANDO',
    'testnet.simulated': 'simulados',
    'testnet.stopSimulation': 'Parar Simulação',
    'testnet.startSimulation': 'Iniciar Simulação',
    'testnet.howToParticipate': 'Como Participar',
    'testnet.howToParticipateDesc': 'Escolha seu papel na rede Pozzer — de operadores ativos a delegadores passivos',
    'testnet.nodeType': 'Tipo de Nó',
    'testnet.whatItDoes': 'O que faz',
    'testnet.needsMachine': 'Precisa de máquina?',
    'testnet.reward': 'Recompensa',
    'testnet.yes': 'Sim',
    'testnet.no': 'Não',
    'testnet.testnetNote': 'Nota da testnet',
    'testnet.testnetNoteDesc': 'Durante a testnet, todos os tipos de nó são simulados — não é necessário máquina real. No lançamento da mainnet, nós Worker e Verifier exigirão o cliente Pozzer e uma NFT License.',
    'testnet.referralProgram': 'Programa de Referência',
    'testnet.referralDesc': 'Convide amigos, ganhe +200 XP cada',
    'testnet.connectForReferral': 'Conecte a carteira para obter seu link de referência',
    'testnet.copied': 'Copiado',
    'testnet.copy': 'Copiar',
    'testnet.invited': 'Convidados',
    'testnet.bonusXP': 'Bônus XP',
    'testnet.pending': 'Pendente',
    'testnet.earnCalculator': 'Calculadora de Ganhos',
    'testnet.earnCalculatorDesc': 'Estime seus retornos potenciais',
    'testnet.launchPrice': 'Preço de Lançamento',
    'testnet.friendsReferred': 'Amigos Indicados',
    'testnet.baseValue': 'Valor Base',
    'testnet.leaderboard': 'Classificação',
    'testnet.rank': 'Posição',
    'testnet.profile': 'Perfil',
    'testnet.inviteReward': 'Bônus Convite',
    'testnet.totalReward': 'Total',
    'testnet.address': 'Endereço',
    'testnet.you': 'VOCÊ',
    'testnet.noLeaderboardYet': 'Nenhum participante ainda. Seja o primeiro!',
    // Mainnet Rewards
    'testnet.rewards.title': 'RECOMPENSAS DA MAINNET POR TIER',
    'testnet.rewards.subtitle': 'Seu nível de XP desbloqueia benefícios exclusivos no lançamento da mainnet',
    'testnet.rewards.yourTier': 'SEU TIER',
    'testnet.rewards.boost': 'Boost',
    'testnet.rewards.needsXP': 'Precisa {{xp}} XP',
    'testnet.rewards.explorer': 'Explorer',
    'testnet.rewards.explorerReward1': 'Airdrop pequeno',
    'testnet.rewards.explorerReward2': 'Acesso à mainnet',
    'testnet.rewards.operator': 'Operator',
    'testnet.rewards.operatorReward1': 'Airdrop médio',
    'testnet.rewards.operatorReward2': 'Top 100: 80% desconto NFT',
    'testnet.rewards.operatorReward3': '1.3x boost de alocação',
    'testnet.rewards.validator': 'Validator',
    'testnet.rewards.validatorReward1': 'Airdrop grande',
    'testnet.rewards.validatorReward2': 'Top 500: 50% desconto NFT',
    'testnet.rewards.validatorReward3': 'Prioridade validador',
    'testnet.rewards.validatorReward4': '1.6x boost de alocação',
    'testnet.rewards.genesis': 'Genesis Operator',
    'testnet.rewards.genesisReward1': 'Airdrop máximo',
    'testnet.rewards.genesisReward2': 'Top 21: NFT License GRÁTIS',
    'testnet.rewards.genesisReward3': 'Slot validador garantido',
    'testnet.rewards.genesisReward4': 'Ranking Top 21',
    'testnet.rewards.genesisReward5': '2x boost de alocação',
    'testnet.rewards.tipTitle': 'Como Funciona o Boost de Alocação',
    'testnet.rewards.tipDesc': 'Seu tier multiplica seu airdrop base. Exemplo: 2000 PZR base × Genesis 2x = 4000 PZR total.',
    'testnet.bridge.xpEarned': 'XP Ganho',
    'testnet.bridge.xpBonus': 'Bônus',
    'testnet.bridge.missionsDone': 'Missões',
    'testnet.bridge.freeNFT': 'NFT Grátis',
    'testnet.bridge.priorityQueue': 'Fila Prioritária',
    'testnet.bridge.moreForPriority': 'para prioridade',
    'testnet.bridge.referralShared': 'Referências',
    'testnet.bridge.topReferrers': 'Top Referenciadores',
    'testnet.bridge.level': 'Nível',
    'testnet.chat.whatIsDepin': 'O que é DePIN?',
    'testnet.chat.howEarn': 'Como ganhar mais?',
    'testnet.chat.referralTips': 'Dicas de referência',
    'testnet.chat.placeholder': 'Pergunte ao DpossAI...',
    'testnet.notif.walletConnected': '✅ Carteira conectada! Bem-vindo à Pozzer Testnet.',
    'testnet.notif.connectFirst': '⚠️ Conecte sua carteira primeiro!',
    'testnet.notif.missionComplete': 'Missão completa!',
    'testnet.notif.linkCopied': '✅ Link de referência copiado!',
    'testnet.notif.onboardingComplete': '🎉 Onboarding completo! Você está pronto para ganhar XP.',
    'testnet.notif.verifyAction': 'Por favor, complete a ação, depois clique em Verificar para reivindicar seu XP',
    // Mission titles
    'testnet.mission.provider': 'Provider Node',
    'testnet.mission.providerDesc': 'Compartilhe recursos de computação',
    'testnet.mission.validator': 'Validador',
    'testnet.mission.validatorDesc': 'Valide transações da rede',
    'testnet.mission.worker': 'Worker Node',
    'testnet.mission.workerDesc': 'Execute tarefas distribuídas',
    'testnet.mission.delegate': 'Delegar para Validador',
    'testnet.mission.delegateDesc': 'Delegue stake para um validador',
    'testnet.mission.install': 'Instalar Software',
    'testnet.mission.installDesc': 'Configure o software do nó',
    'testnet.mission.twitter': 'Seguir no Twitter',
    'testnet.mission.twitterDesc': 'Siga @pozzer_depin',
    'testnet.mission.telegram': 'Entrar no Telegram',
    'testnet.mission.telegramDesc': 'Entre no grupo oficial',
    'testnet.mission.post': 'Postar sobre Pozzer',
    'testnet.mission.postDesc': 'Compartilhe no Twitter',
    'testnet.mission.daily': 'Compartilhamento Diário',
    'testnet.mission.dailyDesc': 'Compartilhe diariamente',
    // Simulators
    'testnet.sim.provider': 'Provider Node',
    'testnet.sim.providerDesc': 'Compartilhe bandwidth & compute',
    'testnet.sim.validator': 'Validator Node',
    'testnet.sim.validatorDesc': 'Valide transações',
    'testnet.sim.worker': 'Worker Node',
    'testnet.sim.workerDesc': 'Processe tarefas distribuídas',
    // Milestones (XP-based levels)
    'testnet.milestone.newbie': 'Novato',
    'testnet.milestone.newbieReward': 'Começando a jornada',
    'testnet.milestone.newbieMainnet': 'Conecte sua carteira para iniciar',
    'testnet.milestone.explorer': 'Explorador',
    'testnet.milestone.explorerReward': 'Acesso aos Simuladores de Nó',
    'testnet.milestone.explorerMainnet': 'Badge de participante da testnet',
    'testnet.milestone.operator': 'Operador',
    'testnet.milestone.operatorReward': 'Dicas avançadas do DpossAI desbloqueadas',
    'testnet.milestone.operatorMainnet': '+15% bônus de alocação mainnet',
    'testnet.milestone.validator': 'Validador',
    'testnet.milestone.validatorReward': 'Fila prioritária NFT License',
    'testnet.milestone.validatorMainnet': 'NFT License grátis na mainnet',
    'testnet.milestone.genesis': 'Genesis Operator',
    'testnet.milestone.genesisReward': 'Slot de validador reservado',
    'testnet.milestone.genesisMainnet': 'Slot de validador + 2x alocação',
    // Onboarding
    'testnet.onboard.wallet': 'Conecte sua carteira',
    'testnet.onboard.walletDesc': 'Vincule sua carteira para começar a ganhar XP',
    'testnet.onboard.dpossai': 'Conheça o DpossAI',
    'testnet.onboard.dpossaiDesc': 'Seu agente IA guiará sua jornada',
    'testnet.onboard.mission': 'Complete sua primeira missão',
    'testnet.onboard.missionDesc': 'Siga-nos no Twitter ou entre no Telegram',
    'testnet.onboard.invite': 'Convide um amigo',
    'testnet.onboard.inviteDesc': 'Compartilhe seu link de referência por +200 XP',
    // Node types
    'testnet.nodeType.worker': 'Worker Node',
    'testnet.nodeType.workerWhat': 'Executa tarefas distribuídas delegadas pela rede',
    'testnet.nodeType.workerReward': 'Recompensa por tarefa executada',
    'testnet.nodeType.verifier': 'Verifier Node',
    'testnet.nodeType.verifierWhat': 'Verifica e valida resultados dos Worker Nodes',
    'testnet.nodeType.verifierReward': 'Recompensa por validação',
    'testnet.nodeType.delegator': 'Delegador',
    'testnet.nodeType.delegatorWhat': 'Empresta tokens para nós aumentarem seu poder de stake',
    'testnet.nodeType.delegatorReward': 'Parte das recompensas do nó',
    'testnet.nodeType.delegating': 'Delegando',
    'testnet.nodeType.delegatingWhat': 'Ação de delegar tokens para um nó ativo',
    'testnet.nodeType.delegatingReward': 'Rendimento passivo em PZR stakado',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
